//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIBrowser.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIBrowser.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button 的本地化字符串。
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CalendarX 的本地化字符串。
        /// </summary>
        public static string CalendarX {
            get {
                return ResourceManager.GetString("CalendarX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CornerRadius 的本地化字符串。
        /// </summary>
        public static string CornerRadius {
            get {
                return ResourceManager.GetString("CornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CustomControls 的本地化字符串。
        /// </summary>
        public static string CustomControls {
            get {
                return ResourceManager.GetString("CustomControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DataGrid 的本地化字符串。
        /// </summary>
        public static string DataGrid {
            get {
                return ResourceManager.GetString("DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateTimePicker 的本地化字符串。
        /// </summary>
        public static string DateTimePicker {
            get {
                return ResourceManager.GetString("DateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DropDown 的本地化字符串。
        /// </summary>
        public static string DropDown {
            get {
                return ResourceManager.GetString("DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foreground 的本地化字符串。
        /// </summary>
        public static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form 的本地化字符串。
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IconFont 的本地化字符串。
        /// </summary>
        public static string IconFont {
            get {
                return ResourceManager.GetString("IconFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ListView 的本地化字符串。
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miscellaneous 的本地化字符串。
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Native Controls 的本地化字符串。
        /// </summary>
        public static string NativeControls {
            get {
                return ResourceManager.GetString("NativeControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold the Ctrl key and click on the example element above to quickly bring up the control palette. 的本地化字符串。
        /// </summary>
        public static string PaletteTips {
            get {
                return ResourceManager.GetString("PaletteTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slider 的本地化字符串。
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SwitchCheckBox 的本地化字符串。
        /// </summary>
        public static string SwitchCheckBox {
            get {
                return ResourceManager.GetString("SwitchCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl 的本地化字符串。
        /// </summary>
        public static string TabControl {
            get {
                return ResourceManager.GetString("TabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeSelector 的本地化字符串。
        /// </summary>
        public static string TimeSelector {
            get {
                return ResourceManager.GetString("TimeSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TreeView 的本地化字符串。
        /// </summary>
        public static string TreeView {
            get {
                return ResourceManager.GetString("TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
