//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIBrowser.Localization.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIBrowser.Localization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 IconFont 的本地化字符串。
        /// </summary>
        public static string IconFont {
            get {
                return ResourceManager.GetString("IconFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoticeX 的本地化字符串。
        /// </summary>
        public static string NoticeX {
            get {
                return ResourceManager.GetString("NoticeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Palette 的本地化字符串。
        /// </summary>
        public static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PendingBoxX 的本地化字符串。
        /// </summary>
        public static string PendingBoxX {
            get {
                return ResourceManager.GetString("PendingBoxX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search controls ... 的本地化字符串。
        /// </summary>
        public static string SearchControlTips {
            get {
                return ResourceManager.GetString("SearchControlTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style Code 的本地化字符串。
        /// </summary>
        public static string StyleCode {
            get {
                return ResourceManager.GetString("StyleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WindowX 的本地化字符串。
        /// </summary>
        public static string WindowX {
            get {
                return ResourceManager.GetString("WindowX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XAML Code 的本地化字符串。
        /// </summary>
        public static string XamlCode {
            get {
                return ResourceManager.GetString("XamlCode", resourceCulture);
            }
        }
    }
}
