//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIBrowser.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Button 的本地化字符串。
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ButtonStyle 的本地化字符串。
        /// </summary>
        public static string ButtonStyle {
            get {
                return ResourceManager.GetString("ButtonStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change If Checked 的本地化字符串。
        /// </summary>
        public static string ChangeContentWhenChecked {
            get {
                return ResourceManager.GetString("ChangeContentWhenChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckBox 的本地化字符串。
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Code Viewer 的本地化字符串。
        /// </summary>
        public static string CloseCodeViewer {
            get {
                return ResourceManager.GetString("CloseCodeViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Code 的本地化字符串。
        /// </summary>
        public static string CopyCode {
            get {
                return ResourceManager.GetString("CopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CornerRadius 的本地化字符串。
        /// </summary>
        public static string CornerRadius {
            get {
                return ResourceManager.GetString("CornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Introduction 的本地化字符串。
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsWaiting 的本地化字符串。
        /// </summary>
        public static string IsWaiting {
            get {
                return ResourceManager.GetString("IsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Native Controls 的本地化字符串。
        /// </summary>
        public static string NativeControls {
            get {
                return ResourceManager.GetString("NativeControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Palette 的本地化字符串。
        /// </summary>
        public static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PasswordBox 的本地化字符串。
        /// </summary>
        public static string PasswordBox {
            get {
                return ResourceManager.GetString("PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadioButton 的本地化字符串。
        /// </summary>
        public static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Icon 的本地化字符串。
        /// </summary>
        public static string ShowIcon {
            get {
                return ResourceManager.GetString("ShowIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Watermark 的本地化字符串。
        /// </summary>
        public static string ShowWatermark {
            get {
                return ResourceManager.GetString("ShowWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SinkWhenClick 的本地化字符串。
        /// </summary>
        public static string SinkWhenClick {
            get {
                return ResourceManager.GetString("SinkWhenClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextBox 的本地化字符串。
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThemeBrush 的本地化字符串。
        /// </summary>
        public static string ThemeBrush {
            get {
                return ResourceManager.GetString("ThemeBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Code 的本地化字符串。
        /// </summary>
        public static string ViewCode {
            get {
                return ResourceManager.GetString("ViewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
