//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIBrowser.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIBrowser.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BaseStyle 的本地化字符串。
        /// </summary>
        public static string BaseStyle {
            get {
                return ResourceManager.GetString("BaseStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button 的本地化字符串。
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calendar 的本地化字符串。
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Carousel 的本地化字符串。
        /// </summary>
        public static string Carousel {
            get {
                return ResourceManager.GetString("Carousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change If Checked 的本地化字符串。
        /// </summary>
        public static string ChangeContentWhenChecked {
            get {
                return ResourceManager.GetString("ChangeContentWhenChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CheckBox 的本地化字符串。
        /// </summary>
        public static string CheckBox {
            get {
                return ResourceManager.GetString("CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChildOnly 的本地化字符串。
        /// </summary>
        public static string ChildOnly {
            get {
                return ResourceManager.GetString("ChildOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clock 的本地化字符串。
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Code Viewer 的本地化字符串。
        /// </summary>
        public static string CloseCodeViewer {
            get {
                return ResourceManager.GetString("CloseCodeViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ComboBox 的本地化字符串。
        /// </summary>
        public static string ComboBox {
            get {
                return ResourceManager.GetString("ComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Code 的本地化字符串。
        /// </summary>
        public static string CopyCode {
            get {
                return ResourceManager.GetString("CopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CornerRadius 的本地化字符串。
        /// </summary>
        public static string CornerRadius {
            get {
                return ResourceManager.GetString("CornerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Countdown 的本地化字符串。
        /// </summary>
        public static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Controls 的本地化字符串。
        /// </summary>
        public static string CustomControls {
            get {
                return ResourceManager.GetString("CustomControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DateTimePicker 的本地化字符串。
        /// </summary>
        public static string DateTimePicker {
            get {
                return ResourceManager.GetString("DateTimePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DropDown 的本地化字符串。
        /// </summary>
        public static string DropDown {
            get {
                return ResourceManager.GetString("DropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpandBehaviour 的本地化字符串。
        /// </summary>
        public static string ExpandBehaviour {
            get {
                return ResourceManager.GetString("ExpandBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expander 的本地化字符串。
        /// </summary>
        public static string Expander {
            get {
                return ResourceManager.GetString("Expander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExpandMode 的本地化字符串。
        /// </summary>
        public static string ExpandMode {
            get {
                return ResourceManager.GetString("ExpandMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GroupBox 的本地化字符串。
        /// </summary>
        public static string GroupBox {
            get {
                return ResourceManager.GetString("GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ImageCuter 的本地化字符串。
        /// </summary>
        public static string ImageCuter {
            get {
                return ResourceManager.GetString("ImageCuter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indeterminate 的本地化字符串。
        /// </summary>
        public static string Indeterminate {
            get {
                return ResourceManager.GetString("Indeterminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Introduction 的本地化字符串。
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsWaiting 的本地化字符串。
        /// </summary>
        public static string IsWaiting {
            get {
                return ResourceManager.GetString("IsWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item Height 的本地化字符串。
        /// </summary>
        public static string ItemHeight {
            get {
                return ResourceManager.GetString("ItemHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ListBox 的本地化字符串。
        /// </summary>
        public static string ListBox {
            get {
                return ResourceManager.GetString("ListBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MultiSelector 的本地化字符串。
        /// </summary>
        public static string MultiSelector {
            get {
                return ResourceManager.GetString("MultiSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Native Controls 的本地化字符串。
        /// </summary>
        public static string NativeControls {
            get {
                return ResourceManager.GetString("NativeControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NeonLabel 的本地化字符串。
        /// </summary>
        public static string NeonLabel {
            get {
                return ResourceManager.GetString("NeonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OnlyOne 的本地化字符串。
        /// </summary>
        public static string OnlyOne {
            get {
                return ResourceManager.GetString("OnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overview 的本地化字符串。
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pagination 的本地化字符串。
        /// </summary>
        public static string Pagination {
            get {
                return ResourceManager.GetString("Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Palette 的本地化字符串。
        /// </summary>
        public static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PasswordBox 的本地化字符串。
        /// </summary>
        public static string PasswordBox {
            get {
                return ResourceManager.GetString("PasswordBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress 的本地化字符串。
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProgressBar 的本地化字符串。
        /// </summary>
        public static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadioButton 的本地化字符串。
        /// </summary>
        public static string RadioButton {
            get {
                return ResourceManager.GetString("RadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectMode 的本地化字符串。
        /// </summary>
        public static string SelectMode {
            get {
                return ResourceManager.GetString("SelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Icon 的本地化字符串。
        /// </summary>
        public static string ShowIcon {
            get {
                return ResourceManager.GetString("ShowIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Percent 的本地化字符串。
        /// </summary>
        public static string ShowPercent {
            get {
                return ResourceManager.GetString("ShowPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Search Box 的本地化字符串。
        /// </summary>
        public static string ShowSearchBox {
            get {
                return ResourceManager.GetString("ShowSearchBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowTickBar 的本地化字符串。
        /// </summary>
        public static string ShowTickBar {
            get {
                return ResourceManager.GetString("ShowTickBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ShowValue 的本地化字符串。
        /// </summary>
        public static string ShowValue {
            get {
                return ResourceManager.GetString("ShowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Watermark 的本地化字符串。
        /// </summary>
        public static string ShowWatermark {
            get {
                return ResourceManager.GetString("ShowWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SingleClick 的本地化字符串。
        /// </summary>
        public static string SingleClick {
            get {
                return ResourceManager.GetString("SingleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SinkWhenClick 的本地化字符串。
        /// </summary>
        public static string SinkWhenClick {
            get {
                return ResourceManager.GetString("SinkWhenClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slider 的本地化字符串。
        /// </summary>
        public static string Slider {
            get {
                return ResourceManager.GetString("Slider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TabControl 的本地化字符串。
        /// </summary>
        public static string TabControl {
            get {
                return ResourceManager.GetString("TabControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TextBox 的本地化字符串。
        /// </summary>
        public static string TextBox {
            get {
                return ResourceManager.GetString("TextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThemeBrush 的本地化字符串。
        /// </summary>
        public static string ThemeBrush {
            get {
                return ResourceManager.GetString("ThemeBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ThumbSize 的本地化字符串。
        /// </summary>
        public static string ThumbSize {
            get {
                return ResourceManager.GetString("ThumbSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeline 的本地化字符串。
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TrackThickness 的本地化字符串。
        /// </summary>
        public static string TrackThickness {
            get {
                return ResourceManager.GetString("TrackThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TreeView 的本地化字符串。
        /// </summary>
        public static string TreeView {
            get {
                return ResourceManager.GetString("TreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using Animation 的本地化字符串。
        /// </summary>
        public static string UsingAnimation {
            get {
                return ResourceManager.GetString("UsingAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Code 的本地化字符串。
        /// </summary>
        public static string ViewCode {
            get {
                return ResourceManager.GetString("ViewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
